### ISSUE TITLE
Zero Size Image String Error

### ISSUE THREAD

**Issue by minorsecond** [cowai/camerarawpreviews#11]
I'm running NC 12.0.3 with PHP 7.0.25 on FreeBSD. I'm getting `Camera Raw Previews: Zero size image string passed` when trying to preview a .dng file.

I'm thinking [this](https://stackoverflow.com/questions/23289057/imagick-code-imagemagick-not-working) is related, specificially this:

> $im2->setImageFormat('gif');
> // ...
> $frame->readImageBlob($im2);

I've poked around in RawPreview.php but couldn't get anything resolved.

Have you run into anything like this?

**Comment by cowai** [comment]
I have not run into this. What format are you trying to preview?
You can check if you can get an image out of exiftool. It may use other tags for your format.

**Comment by cowai** [comment]
@minorsecond  Feel fry to try latest master now, multiple things are fixed.
