### ISSUE TITLE
JPG Previews

### ISSUE THREAD

**Issue by Tott3** [cowai/camerarawpreviews#16]
Not sure if it's this app, but my JPG previews has stopped working ;o The RAW works just fine tho. This is the only unofficial app I'm running.

**Comment by cowai** [comment]
Any info from the logs?

**Comment by Tott3** [comment]
Pretty much all I could find in the error_log. Not quiet sure what other logs to be looking for :P 

```
[Mon Apr 09 19:54:09.347190 2018] [fcgid:warn] [pid 5877:tid 140287909287680] [client 83.255.109.195:64428] mod_fcgid: read data timeout in 40 seconds
[Mon Apr 09 19:54:09.347248 2018] [core:error] [pid 5877:tid 140287909287680] [client 83.255.109.195:64428] End of script output before headers: remote.php
```

**Comment by cowai** [comment]
Errors in the nextcloud log would be great.

**Comment by Tott3** [comment]
Found it. This is literally the entire file. Doesn't looks like it got something to do with the thumbnail generation :/ Looks like when I had problems setting up NC the other day :P

`{"reqId":"ZRQwBX78bYSclCqVZnyF","level":3,"time":"2018-04-06T14:40:54+00:00","remoteAddr":"83.255.109.195","user":"--","app":"PHP","method":"POST","url":"\/index.php","message":"mkdir(): Permission denied at \/home\/laddad\/domains\/subdom.laddad.net\/public_html\/lib\/private\/Setup.php#299","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":""}
`

**Comment by Tott3** [comment]
Ye, removing this from the config makes it preview other media files again.

```
  'enabledPreviewProviders' => 
  array (
    0 => 'OCA\\CameraRawPreviews\\RawPreview',
    1 => 'OCA\\CameraRawPreviews\\IndesignPreview',
  ),
```

**Comment by Tott3** [comment]
It's working now. So I removed the lines I posted above from the config and went to "Apps" and hit enable instead. Weird.

**Comment by cowai** [comment]
@Tott3 Can you upload/create a new raw file to check if new files also can be previewed? The previews are cached.

**Comment by Tott3** [comment]
Done. Works like a charm =)

**Comment by cowai** [comment]
@Tott3 Thanks for your input.
Removed info about the config.
https://github.com/cowai/camerarawpreviews/commit/04ef7cc4f24dc81de5c7affff4094a6136028401
I think this was only needed some time ago in older versions.

**Comment by Tott3** [comment]
Cool! Keep up the good work! Awesome tools for a hobby photographer :D
