### ISSUE TITLE
DNG files - Unable to find preview data

### ISSUE THREAD

**Issue by AdamEC** [cowai/camerarawpreviews#17]
Hey, apparently my server can't generate previews of DNG files. Y tried with NEF files, and is working just fine, so I don't know if is because DNG is not supported (haven't found if there is a list of supported formats), or something else is broken on my end.

The logs will just return `Camera Raw Previews: Unable to find preview data` when trying to preview any DNG file, and the preview will be loading forever with a warning error about not being a preview available.

I also tried multiple DNG files from multiple cameras and sources, without any results...

**Comment by cowai** [comment]
@AdamEC Do you know if your DNG files have previews in them? You could upload a test here: https://boxigy.com/s/ps66JnKVM0aUZe9 and I could check it if you want.

**Comment by cowai** [comment]
The file you sent had a tiff preview and not a jpeg preview. I am testing locally to get tiff running, but that will only work if you have php imagick module installed. I need to think about how this could work for those with GD as well.

**Comment by AdamEC** [comment]
Aha, ok! I didn't want to install imagick, but I guess I'll just have to do it now...
Thanks for the help!

**Comment by AdamEC** [comment]
@cowai So... I installed imagick, an Nextcloud is now recognizing it (the theming tab is no longer asking me to install it to support SVG images, for example) but I still get the no preview data error.

Do you know if I need to configure it somewhere else?

**Comment by cowai** [comment]
@AdamEC The code for TIFF previews is now pushed and a new release is pushed to the nextcloud app store. Right now the code does not check if you have TIFF support in imagick or not, but that is another issue. Let me know if the v0.5.3 works for you.

**Comment by AdamEC** [comment]
Updated to v0.5.3, now all my DNG files have beautiful previews.
Thank you so much for the help, and the update!

**Comment by cowai** [comment]
@AdamEC Good to hear it is working for you. Let me know if you find any other issues.
