### ISSUE TITLE
nextcloud issue

### ISSUE THREAD

**Issue by svidpet** [cowai/camerarawpreviews#18]
Hi,

nextcloud stucks into maintance mode during camerarawpreviews update. NC is 13.0.2 on debian 9.

**Comment by cowai** [comment]
Do you find anything related in the logs?

---- On Wed, 23 May 2018 17:02:27 +0200 notifications@github.com wrote ----

Hi,

nextcloud stucks into maintance mode during camerarawpreviews update. NC is 13.0.2 on debian 9.

**Comment by cowai** [comment]
@svidpet Did you install the app via the nextcloud app store?

**Comment by svidpet** [comment]
@ cowai,
Sorry for the late reply. The app was installed through the "notification bell", as I received a note on available update.
NC froze and stuck into maintenance mode. I don't know what has happened, but the value of "maintenance" turned into => true, in the config.php.
After setting it back to false, NC start up as it should, and the installation of the app for the second time was flawless.
Sorry for the fake alarm and thank you so much for your work and quick response.
Please close or delete this issue.
Again, sorry for any inconvenience.

**Comment by cowai** [comment]
@svidpet glad it worked out. Thank you for your nice comments.
