### ISSUE TITLE
Release in ownCloud Marketplace

### ISSUE THREAD

**Issue by michaelstingl** [cowai/camerarawpreviews#19]
I'd love to have this working in ownCloud too. (oC10+)

**Comment by cowai** [comment]
@michaelstingl it would probably work if you download a release and add the neccesary xml.   I would accept a PR for that:)

**Comment by cowai** [comment]
@michaelstingl I saw your title now. Yes that would be preferable. I can look into this in the future.

**Comment by michaelstingl** [comment]
I'll do some testing, also posted a Bounty for it:
https://www.bountysource.com/issues/60530680-release-in-owncloud-marketplace

**Comment by cowai** [comment]
The app is out now on ownCloud Marketplace: https://marketplace.owncloud.com/apps/camerarawpreviews

**Comment by michaelstingl** [comment]
Awesome, thanks!
