### ISSUE TITLE
ARW-Format (RAW Picture from Sony)

### ISSUE THREAD

**Issue by merlincom** [cowai/camerarawpreviews#21]
Felicitation to the developers for excellent work!
It would be very helpful, if you integrate the ARW-Format* for previews in OwnCloud too, because I use OwnCloud for sharing my fotos with my buddy.  
Thank you.

* ARW is the RAW-Format from Sony, for example ILCE-/M2 (Alpha 7 II).

**Comment by cowai** [comment]
@merlincom Could you provide me with a sample. I have tested some arw, and those worked fine for me.

**Comment by merlincom** [comment]
[DSC01422.zip](https://github.com/cowai/camerarawpreviews/files/2253608/DSC01422.zip)
Hallo Ari, is this File (packed as Zip) helpful? 
Greetings from Switzerland

**Comment by cowai** [comment]
Hi, i just tested your file. It works fine in my setup. Could you provide a bit more info? Like OS, CPU architecture. Make sure you have perl installed and see if it helps.

**Comment by cowai** [comment]
@merlincom Also, you you check the nextcloud log for any errors related to camerarawpreviews?

**Comment by merlincom** [comment]
In OwnCloud, there is no error-message in owncloud/data
perl 	ist installed at /usr/local/bin/perl (Free BSD)
https://support.hostpoint.ch/de/produkte/webhosting/haeufig-gestellte-fragen/pfade-verzeichnisse-system.
Now I will install NextCloud and test, if it work.

**Comment by merlincom** [comment]
After installing Nextcloud 13.0.5 and add the apps Camera RAW Previews, it work fine with the ARW-Files from Sony. **Thank Ari for great work and support and stein2k for inspiration**.

PS: For OwnCloud, I found a note, that it could give troubles with FreeBSD. But I am not shure, if this is the reason, that in my case in OwnCloud the app Camera RAW Previews do not work with ARW-Files. 
German: Das Betriebssystem FreeBSD legt die meisten Applikationen unter/usr/local/bin/ anstelle des in der UNIX-Welt gebräuchlichen/usr/bin/ ab.

**Comment by cowai** [comment]
@merlincom which camera raw previews version did you use in ownCloud? I had an issue with freebsd/owncloud last week but that was resolved in 0.5.5.

If you want to still use freebsd/owncloud, make sure "perl" works in the command line. I am also willing to have a look with SSH if you want to debug this.

**Comment by merlincom** [comment]
Hallo ari, did you get my informations in PM about lohin datas?

**Comment by crypdick** [comment]
@ariselseng my preview generation fail with perl errors, even though I have perl and perl-base installed. Any ideas?

```
2019-10-31T23:22:02+00:00 Generating previews for /d/files/dcloud/Images/D Photography/2019 NZ/DSC06517.ARW
Can't load '/usr/lib/x86_64-linux-gnu/perl-base/auto/File/Glob/Glob.so' for module File::Glob: /usr/lib/x86_64-linux-gnu/perl-base/auto/File/Glob/Glob.so: failed to map segment from shared object at /usr/lib/x86_64-linux-gnu/perl-base/XSLoader.pm line 95.
 at /usr/lib/x86_64-linux-gnu/perl-base/File/Glob.pm line 68.
Compilation failed in require at /var/snap/nextcloud/16296/nextcloud/extra-apps/camerarawpreviews/vendor/jmoati/exiftool-bin/exiftool line 886.
BEGIN failed--compilation aborted at /var/snap/nextcloud/16296/nextcloud/extra-apps/camerarawpreviews/vendor/jmoati/exiftool-bin/exiftool line 886.
Undefined subroutine &main::SetWindowTitle called at /var/snap/nextcloud/16296/nextcloud/extra-apps/camerarawpreviews/vendor/jmoati/exiftool-bin/exiftool line 321.
END failed--call queue aborted at /var/snap/nextcloud/16296/nextcloud/extra-apps/camerarawpreviews/vendor/jmoati/exiftool-bin/exiftool line 886.
```

**Comment by ariselseng** [comment]
Not exactly but it sounds like confinement issues with the snap. I have never tried my app with snap. I remember there was another user reporting similar issues with snap.

**Comment by crypdick** [comment]
@ariselseng Do you think that a symlink in `/var/snap/nextcloud/...` may do the trick?

**Comment by ariselseng** [comment]
@crypdick Honestly I have no idea how snap works so I could not tell you.

**Comment by crypdick** [comment]
@ariselseng AFAIK, it essentially installs the app in it's own directory along with all its dependencies.

Could you help me decipher the perl error above? Is there a dependency that seems to be missing?

**Comment by ariselseng** [comment]
@crypdick please try this command that is listed in this comment: https://github.com/ariselseng/camerarawpreviews/issues/29#issuecomment-453753365
The output of that help determine what is wrong.

**Comment by crypdick** [comment]
```
cd /var/snap/nextcloud/current/nextcloud/extra-apps 
# got permission denied. trying again with root
sudo su
cd /var/snap/nextcloud/16296/nextcloud/extra-apps/camerarawpreviews
perl ./vendor/jmoati/exiftool-bin/exiftool -json -preview:all /home/richard/test.ARW
```

output:
```
[{
  "SourceFile": "/home/richard/test.ARW",
  "PreviewImage": "(Binary data 761730 bytes, use -b option to extract)",
  "ThumbnailImage": "(Binary data 8202 bytes, use -b option to extract)"
}]
```

**Comment by ariselseng** [comment]
Hmm. That seemed to work. But I think maybe the perl is local and not what the snap has access to. Is there a perl inside the snap. Its important to execute this as if it was the app doing it.

**Comment by crypdick** [comment]
I'm not sure how to do that. P.S. `/usr/lib/x86_64-linux-gnu/perl-base/XSLoader.pm` is missing.

**Comment by sieman-saa** [comment]
> @ariselseng my preview generation fail with perl errors, even though I have perl and perl-base installed. Any ideas?
> 
> ```
> 2019-10-31T23:22:02+00:00 Generating previews for /d/files/dcloud/Images/D Photography/2019 NZ/DSC06517.ARW
> Can't load '/usr/lib/x86_64-linux-gnu/perl-base/auto/File/Glob/Glob.so' for module File::Glob: /usr/lib/x86_64-linux-gnu/perl-base/auto/File/Glob/Glob.so: failed to map segment from shared object at /usr/lib/x86_64-linux-gnu/perl-base/XSLoader.pm line 95.
>  at /usr/lib/x86_64-linux-gnu/perl-base/File/Glob.pm line 68.
> Compilation failed in require at /var/snap/nextcloud/16296/nextcloud/extra-apps/camerarawpreviews/vendor/jmoati/exiftool-bin/exiftool line 886.
> BEGIN failed--compilation aborted at /var/snap/nextcloud/16296/nextcloud/extra-apps/camerarawpreviews/vendor/jmoati/exiftool-bin/exiftool line 886.
> Undefined subroutine &main::SetWindowTitle called at /var/snap/nextcloud/16296/nextcloud/extra-apps/camerarawpreviews/vendor/jmoati/exiftool-bin/exiftool line 321.
> END failed--call queue aborted at /var/snap/nextcloud/16296/nextcloud/extra-apps/camerarawpreviews/vendor/jmoati/exiftool-bin/exiftool line 886.
> ```

I have the same problem, don't you figure out how to solve it?

**Comment by ariselseng** [comment]
It is definitely due to snap.
