### ISSUE TITLE
NextCloud Update to 0.5.6 failed

### ISSUE THREAD

**Issue by merlincom** [cowai/camerarawpreviews#24]
Camera RAW Previews
Beschreibung anzeigen…
[1] Für diese App ist eine Aktualisierung verfügbar (to (0.5.6).
[2] Update never ends. 
Message:
Diese Nextcloud-Instanz befindet sich gerade im Wartungsmodus, was eine Weile dauern kann.
Diese Seite aktualisiert sich automatisch, wenn die Nextcloud-Instanz wieder verfügbar ist.
Login is not possible.
config/config.php
change 'maintenance' => true, to 'maintenance' => false,
Login is now again possible, but Camera RAW works mo longer and show me the message, that ist some update possible -> [1] But update don't work -> [2] 
Remark: The version 0.5.5 had work perfect.
SOS-Solution:
Rename the folder apps/camerarawprewiews to apps/camerarawprewiews.bak and then activate the app camerarawprewiew in the backend again > and it work.

**Comment by cowai** [comment]
I think that happens sometime because of the app size (6mb) and some timeouts. It has nothing todo with this version specifically.
