### ISSUE TITLE
Support for Nextcloud 15

### ISSUE THREAD

**Issue by violoncelloch** [cowai/camerarawpreviews#27]
Nextcloud 15 has been released today. It would be nice if you could update this app to work on Nextcloud 15! Thank you!

**Comment by cowai** [comment]
@violoncelloch PR is welcome. I am very busy at the moment. It might take a few more days if nobody else fixes it.

**Comment by cowai** [comment]
@jia2258 I am supporting any file that has embedded jpeg/tiff previews inside them and which is supported by exiftool.

**Comment by YellowTech** [comment]
A hack to get it working on 15 again is to just set the `max-version` in `appinfo/info.xml` to 15 instead of 14. It works on my 2 instances. WARNING: I don't know how the app works, this could have consequences.

**Comment by violoncelloch** [comment]
I think that works if there are no (UI) regressions because of changed things in Nextcloud 15... 
@YellowTech could you do a PR for this?

**Comment by YellowTech** [comment]
@violoncelloch just did it.

**Comment by violoncelloch** [comment]
@YellowTech thank you for the PR #28
@cowai is this sufficient for you and could you release a new version to the nextcloud appstore then?

**Comment by cowai** [comment]
@violoncelloch Fixed by @YellowTech. I have signed it and put it to the nextcloud app store.
