### ISSUE TITLE
No previews generated for DNG 

### ISSUE THREAD

**Issue by svenb1234** [cowai/camerarawpreviews#29]
I use nextcloudpi with the app but there are no previews generated for the DNG files the Android app open camera shoots. Unfortunately I cannot find any messages in the logs, thus I am not even sure the app is working. How can I find out.? Nextcloudpi is supposedly pre-configured with imagemagick. The logs only contain debug output of the normal gallery app preview generator which fails to process the DNG files.

I would upload a sample but GitHub apparently does not allow DNG as attachment.

**Comment by cowai** [comment]
This app doesn't necessarily need imagemagick. It works mostly with GD as well. The main dependency is perl and being able to extract previews with the included exiftool in this app. Plus, the raw file needs to have previews embedded in the exif tags as well. Some DNG do not have that.
 
To test that exiftool works and that the DNG file have previews you can try this command in your terminal:
```shell
$ cd nextcloud/apps/camerarawpreviews
$ perl ./vendor/jmoati/exiftool-bin/exiftool -json -preview:all TESTFILE.DNG

**Comment by cowai** [comment]
@svenb1234 Any news here?

**Comment by svenb1234** [comment]
Sorry for the late answer, I missed the first notification.

The output I get is as follows:

root@nextcloudpi:/data/nextcloud/apps/camerarawpreviews# perl ./vendor/jmoati/exiftool-bin/exiftool -json -preview:all /data/nextcloud/data/__groupfolders/1/IMG_20181203_172003.dng
[{
  "SourceFile": "/data/nextcloud/data/__groupfolders/1/IMG_20181203_172003.dng"
}]
root@nextcloudpi:/data/nextcloud/apps/camerarawpreviews#

**Comment by cowai** [comment]
These files do not have previews embedded inside them I'm afraid. If you  use Lightroom or something like that you can usually enable previews to be generated when dumping the files or maybe on the camera itself.

**Comment by svenb1234** [comment]
Ok, then I misunderstood the functionality of the app. Thought it would actually create previews rather than only extract them. Never mind.

**Comment by cowai** [comment]
Yes I am sorry. Most raw files does have previews inside them though. It's basically just DNG I think that some times does not, depending on the import method used from the cameras.
I am closing this.
You could create another issue for getting this functionality of creating previews without exiftool though.
