### ISSUE TITLE
Force preview

### ISSUE THREAD

**Issue by jsanfe** [cowai/camerarawpreviews#30]
Its possible to force preview? I mean, I have a lot of raws, I have to wait a lot in each folder to make the previews. I dont know if is possible to force this, and allow next cloud to generate the raws previews for all folders...

Regards!

**Comment by cowai** [comment]
https://apps.nextcloud.com/apps/previewgenerator

You can use this. Only down side I remember was it generates like 10-15 previews for each file. At the company I work we have 300k+ images, and with that I got over 3 million extra items in the filecache slowing everything down ;)

Maybe Preview Generator now can specify image sizes that should be generated though.

Another thing that I have been thinking of is caching of a highest-possible quality jpeg for some time that can be used as a starting point for all sizes in camerarawpreviews. Right now, it extracts the original preview from the raw file everytime.
