### ISSUE TITLE
exif_read_data errors - Illegal format code

### ISSUE THREAD

**Issue by dennorske** [cowai/camerarawpreviews#32]
`exif_read_data(DSC_0114.NEF): Process tag(x0003=UndefinedTa): Illegal pointer offset(x0003 &lt; xA2221002) at /var/snap/nextcloud/12753/nextcloud/extra-apps/metadata/lib/Controller/MetadataController.php#215`

I get a bunch of these and no previews ever worked on my installation.
i am running nextcloud as a snap.

Memory limit is around 16 gb, imagemagic has been installed.
Any idea what I can do to test/make it work for my lovely .NEF pictures? :)

**Comment by cowai** [comment]
If you send me a sample I can have a look;)

**Comment by dennorske** [comment]
Here is the exact file as described above. Picture shows Tromsø's bridge (Norsk wohoo)
http://ducky.rocks/index.php/s/SfWwXSLDSjTt9aQ/download

Will expire tomorrow

**Comment by cowai** [comment]
@dennorske Seems to be a snap issue. Maybe some kind of snap permissions issue or SELinux issue. It works great here using docker. I can test this in time, but not before at least a week I think.

**Comment by dennorske** [comment]
@cowai alrighty, take your time. I'd be happy to help with logs etc. if you need.
Keep me updated :)

**Comment by dennorske** [comment]
hi @cowai! I hope you are doing well :)
Any news on the testing, and is there anything else i can provide?

**Comment by cowai** [comment]
No news yet. I think I will be able to test this weekend.

**Comment by cowai** [comment]
@dennorske I tried it now. It seems to work without issues?
I did these steps on arch (and this is maybe the problem. No SELinux):

Can you confirm that use tried this app by doing something like these steps?

1:
```shell
$ sudo snap install nextcloud
```
2:
created a admin user with default settings in the web ui.

3: installed camera raw previews with the web ui

4: uploaded a raw file.

5: everything works without any issues in the logs.

**Comment by dennorske** [comment]
I am sorry for the long response time here. 
I ended up moving over to the normal install of nextcloud, as i needed to configure it to my needs much easier. There i reinstalled my apps. And Voila!

I can now see all the raws be processed and shown thumbnails for, and I can even preview the files in the web-browser which is great. Thanks, I am closing this issue for now.

If other people face the same issue, I will be helping out with research - but for now I am letting it be since it works. Great job with the app, glad it exists :)
