### ISSUE TITLE
nc16.0.1rc1

### ISSUE THREAD

**Issue by hezten** [cowai/camerarawpreviews#33]
After ugpradering to nc16.0.1.rc1 the previews in thumbnail view links to download of the files, not the fullsize preview. Is there any way to fix this ? Gallery view works fine, but the fullsize previews if prefered. The fullsize preview works fine with jpg and regular image format.

**Comment by cowai** [comment]
@hezten Integration with the new Nextcloud Viewer is coming soon.

**Comment by hezten** [comment]
@cowai coool, looking forward to it. Im using NC for cloud of all my raw files (30tb+) and several hundreds of thousand raw files so this is a very welcome updated integration :-)

**Comment by cowai** [comment]
@hezten Wow that's a lot. You must have a huge oc_filecache?

**Comment by cowai** [comment]
@hezten A new release submitted to the appstore now.

**Comment by Skeebopstop** [comment]
Hi @ariselseng , I am running into this same issue but am on the latest release as per Nextcloud 19.0.4. Could it be my oc_filecache? My previews show fine, but when I click on the file it downloads rather than shows up in viewer, but the thumbnails show the previews. 

Any help appreciated!

**Comment by Skeebopstop** [comment]
I can confirm this works for me, thanks so much! Do you know if it's something related to this as to why camera raw preview do not show up in the 'Photos' app? Everything works great via the 'Files' app.

Thanks!

**Comment by ariselseng** [comment]
I bet the Photos app does not check if a file has preview but rather just the mime type.

**Comment by Skeebopstop** [comment]
thanks, agreed. I put a post under the Photos app github and they've confirmed it only supports png/jpg. I've requested they just show all 'image' mimetypes as that's a bit ridiculous otherwise.
