### ISSUE TITLE
High CPU wait generating .CR2 previews

### ISSUE THREAD

**Issue by cvinhaes** [cowai/camerarawpreviews#34]
During preview generation CPU wait (top wa) stay above 50% most of the time while the preview generation process or any other active process won't tax the CPU more than 5 to 10%. Load average in 5 minutes goes as high as 5 in a Celeron dual core CPU (J1800) with 4GB RAM running on Linux omv 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64 GNU/Linux. I would understand if I saw high CPU load due to the conversion but it seem that the poor performance of about 1 minute per CR2 photo is mostly I/O wait when the actual I/O is very low - mostly below 500KB/s with occasional spikes.
Generating previews for JPGs works jus fine and very quickly.

**Comment by cowai** [comment]
This is interesting data. I have never tried my app on anything other than beefy intel i7s so I never see 1 minute conversion times. What kind of storage are you using?

**Comment by cvinhaes** [comment]
It's an old PC converted to NAS server, storage is a local Hitachi SATA 7200 rpm 2TB HD. My point is exactly that I expected conversion to overwhelm the CPU but this is not what I see. Important to mention that I'm running the official nextcloud 16 Docker image.

**Comment by cvinhaes** [comment]
![image](https://user-images.githubusercontent.com/50474774/60375745-26d9a580-99e1-11e9-865d-d1702a278c3e.png)

**Comment by cowai** [comment]
For each file it's copied to /tmp (to support external storage), maybe it's that part that is really slow. Can you if your drive is overwhelmed? Iostat or some other utility. I bet there is multiple files being copied at the same time and your drive cannot keep up.

**Comment by cvinhaes** [comment]
sdb is the system disk (solid state), sdc (magnetic) is where the preview files are stored and where sdd (magnetic) is where the source pictures live. This is what looks odd to me - sometimes the system spend minutes with no access to sdc or sdd (I can hear when there's activity) while the system disk is overwhelmed just as seen on this picture, this is when the load average and i/o wait spikes. After awhile I can hear the reading / writing again, the load average and wait going down for some time until back to the first state again. It cycles over and over.

![image](https://user-images.githubusercontent.com/50474774/60404700-b6b65580-9b81-11e9-8639-afcf6b2cba32.png)

**Comment by cvinhaes** [comment]
![image](https://user-images.githubusercontent.com/50474774/60404857-08131480-9b83-11e9-895b-3ba32e2286b8.png)

**Comment by cvinhaes** [comment]
![image](https://user-images.githubusercontent.com/50474774/60404866-119c7c80-9b83-11e9-90d1-e6f92b147065.png)
![image](https://user-images.githubusercontent.com/50474774/60404872-1d883e80-9b83-11e9-9658-e949df47ae96.png)

**Comment by cvinhaes** [comment]
[lsof.txt](https://github.com/cowai/camerarawpreviews/files/3343595/lsof.txt)
The attached file is the lsof output for the preview:generate-all process.

**Comment by cowai** [comment]
@cvinhaes What is apache doing when its at 100%? The preview:generator should be totally separated from apache.

**Comment by cvinhaes** [comment]
@cowai there's definetly something weird with apache here because it`s also maxing out when I sync files using the nextcloud desktop client. Same deal, high cpu and little to none actual I/O throughput, so I guess the issue with raw cr2 preview is unrelated with the camerarawpreviews app. I'm closing the issue for now, thank you for your attention.

**Comment by cowai** [comment]
@cvinhaes Did you try disabling this app and see if you still had 100% cpu ?

**Comment by cvinhaes** [comment]
@cowai yes I have. Preview works perfectly with the app disabled and CPU load remains well under control.
