### ISSUE TITLE
sh: exiftool: command not found

### ISSUE THREAD

**Issue by Whisprin** [cowai/camerarawpreviews#5]
Hello,

this app wasn't working for me. After some digging around, I found out that `exiftool` cannot be found from the shell in `shell_exec`.
```
sh: exiftool: command not found
```

My fix was to call exiftool using the full path as returned by `OC_Helper::findBinaryPath`.

Here's my pull reqeust: https://github.com/cowai/camerarawpreviews/pull/4

**Comment by cowai** [comment]
Merged your pull request #4. Thanks!
