### ISSUE TITLE
Check for rotation exif tags and rotate accordingly

### ISSUE THREAD

**Issue by cowai** [cowai/camerarawpreviews#7]

**Comment by hasherdk** [comment]
I submitted a pull request addressing this issue.

https://github.com/cowai/camerarawpreviews/pull/10

**Comment by steiny2k** [comment]
The code from the pull request lacks the definition of the converter local variable in the new method  rotateImageIfNeeded, and so it doesn't work.
Adding `$converter = \OC_Helper::findBinaryPath('exiftool');` at the very beginning fixes this.

**Comment by cowai** [comment]
Thanks for PR.
Is this fully working now?

**Comment by steiny2k** [comment]
yes, at least in my setup the rotation seems to do the right thing. I've only tested Sony ARW files though. Don't know what it does with other raw formats.

**Comment by cowai** [comment]
Nobody has complained. I think it works :)
