### ISSUE TITLE
Can't enable app

### ISSUE THREAD

**Issue by rosmoo** [cowai/camerarawpreviews#9]
As instructed, I copied and extracted file to Nextcloud/Apps. After fixing permission, I tried to enable app from disabled apps section. At this point Nextcloud threw error :Could not download app camerarawpreviews".  Any reason why?

Nextcloud version: 12.0.3

**Comment by cowai** [comment]
I am running 12.0.3 and do not have this issue. Have you checked the log? Or maybe try enabling with the cli "occ" ?

**Comment by rosmoo** [comment]
I got it to work with with occ. Thanks!
